### ISSUE TITLE
Information ra 6500 iq

### ISSUE THREAD

**Issue by DeltaFox0018** [galletn/iaqualink#16]
Hello,
I have a ra 6500 iq is after configuring the integration I only see that the robot is online but I don't see any other data

How do I display the other data like when is it until the end of cleaning or filter status?

Thanks

i have only this sensor
<img width="1473" alt="image" src="https://github.com/galletn/iaqualink/assets/35847603/f29fbcbd-9654-48a1-8dd9-f02962763d07">

**Comment by galletn** [comment]
Hi,

if you click on it you should be able to see the attributes:

![image](https://github.com/galletn/iaqualink/assets/21059110/c4e32bba-b435-4ff5-8a09-495a00db5603)


You can create a card like this:

![image](https://github.com/galletn/iaqualink/assets/21059110/bd48f747-a837-4105-b0cd-d43a84a094d1)


code bellow:

you can use attributes in the dashboards:



```
type: entities
entities:
  - entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    icon: mdi:robot-mower
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: robot_name
    name: Pool Robot Name
    icon: mdi:pool
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: model
    name: Model
    icon: mdi:numeric
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: serial_number
    name: Serial Number
    icon: mdi:ticket-confirmation-outline
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: last_online
    name: Last Online
    icon: mdi:connection
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: temperature
    name: Temperature
    icon: mdi:pool-thermometer
    suffix: °c
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: total_hours
    name: Total Hours
    icon: mdi:robot-mower-outline
    suffix: h
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: error_state
    name: Error State
    icon: mdi:list-status
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: cycle_start_time
    name: Last StartTime
    icon: mdi:calendar
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: canister
    name: Canister
    icon: mdi:robot-vacuum-variant
  - type: attribute
    entity: sensor.iaqualinkrobots_ra_6570_iq_bobby_2
    attribute: running
    name: Running
    icon: mdi:play-box-multiple
header:
  type: picture
  image: /local/RA6570.jpg
  tap_action:
    action: none
  hold_action:
    action: none
```

you could also create template sensors from the attributes. please have a look on google for that one, many examples exist
